### ISSUE TITLE
Raspberry PI example crashes on startup

### ISSUE THREAD

**Issue by FredRooks** [OpenSmartEnvironment/ose-example-rpi#1]
After installing the Raspberry Pi example on Raspbian 8.0 running Node v4.1.1, ./bin/run.js crashes with the following output:

<pre><code>
ose@brehm ~/ose-example-rpi $ ./bin/run.js 
1444066639 'NOTICE | ose | Reading configuration, creating plugins ...'
1444066640 'NOTICE | ose | Plugins created, calling `config()` ...'
1444066642 'NOTICE | ose | New space |' 'example.org'
1444066642 'NOTICE | ose | Plugins configured, calling dependencies ...'
1444066642 'WARNING | ose | Change URL in instance configuration of the following peer:  |' 'player'
1444066642 'NOTICE | ose | HTTP server started |' { ip: 'all', port: 4432 }
1444066642 'NOTICE | ose | WebSockets server started'
1444066642 'DEBUG | ose | State patched |' '{"entry":"rpi","state":{"pins":{},"pinTypes":{"din":{"name":"din"},"dout":{"name":"dout"}}}}'
1444066642 'DEBUG | ose | State patched |' '{"entry":"switch1","state":{"debounce":50,"tap":800,"hold":1000}}'
1444066642 'DEBUG | ose | State patched |' '{"entry":"heater1","state":{"enabled":false}}'
========================================================
1444066653 'ERROR | ose | undefined |' 'Cannot read property \'unexport\' of undefined'
Stack Trace:
TypeError: Cannot read property 'unexport' of undefined
    at Object.releaseGpio [as release] (/home/ose/ose-example-rpi/node_modules/ose-rpi/lib/rpi/node.js:304:11)
    at Object.exports.close (/home/ose/ose-example-rpi/node_modules/ose-control/lib/pin/index.js:435:15)
    at /home/ose/ose-example-rpi/node_modules/ose-control/lib/pin/index.js:283:12
    at /home/ose/ose-example-rpi/node_modules/ose-control/lib/pin/switch.js:35:7
    at done (/home/ose/ose-example-rpi/node_modules/ose-control/lib/pin/index.js:372:7)
    at /home/ose/ose-example-rpi/node_modules/ose-rpi/lib/rpi/node.js:228:7
    at setup (/home/ose/ose-example-rpi/node_modules/ose-rpi/lib/rpi/node.js:256:7)
    at setup (/home/ose/ose-example-rpi/node_modules/ose-rpi/lib/rpi/node.js:252:20)
    at setup (/home/ose/ose-example-rpi/node_modules/ose-rpi/lib/rpi/node.js:252:20)
    at setup (/home/ose/ose-example-rpi/node_modules/ose-rpi/lib/rpi/node.js:252:20)
--------------------------------------------------------
Logged at:
Trace
    at Object.exports.error.exports.err (/home/ose/ose-example-rpi/node_modules/ose/lib/logger.js:276:11)
    at process.onError (/home/ose/ose-example-rpi/node_modules/ose/lib/node.js:98:9)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
    at process._fatalException (node.js:211:26)
========================================================
========================================================
1444066653 'ERROR | control | UNEXPECTED |' 'Removed'
Data: undefined
Class Name: /home/ose/ose-example-rpi/node_modules/ose/lib/shard/index.js
Identity: { sid: 7, space: 'example.org' }
Stack Trace:
Error: Removed
    at Object.exports.error (/home/ose/ose-example-rpi/node_modules/ose/lib/wrap.js:579:16)
    at EventEmitter.exports.lhsInited (/home/ose/ose-example-rpi/node_modules/ose/lib/subject.js:229:28)
    at cbShard (/home/ose/ose-example-rpi/node_modules/ose/lib/space/index.js:556:17)
    at EventEmitter.<anonymous> (/home/ose/ose-example-rpi/node_modules/ose/lib/space/index.js:561:7)
    at EventEmitter.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at EventEmitter.exports.setLhs (/home/ose/ose-example-rpi/node_modules/ose/lib/subject.js:94:8)
    at EventEmitter.exports.remove (/home/ose/ose-example-rpi/node_modules/ose/lib/subject.js:40:8)
    at EventEmitter.exports.cleanup (/home/ose/ose-example-rpi/node_modules/ose/lib/space/index.js:343:22)
--------------------------------------------------------
Logged at:
Trace
    at Object.exports.error.exports.err (/home/ose/ose-example-rpi/node_modules/ose/lib/logger.js:276:11)
    at /home/ose/ose-example-rpi/node_modules/ose-rpi/lib/camera/node.js:32:13
    at Object.exports.error (/home/ose/ose-example-rpi/node_modules/ose/lib/link.js:597:5)
    at EventEmitter.exports.lhsInited (/home/ose/ose-example-rpi/node_modules/ose/lib/subject.js:229:12)
    at cbShard (/home/ose/ose-example-rpi/node_modules/ose/lib/space/index.js:556:17)
    at EventEmitter.<anonymous> (/home/ose/ose-example-rpi/node_modules/ose/lib/space/index.js:561:7)
    at EventEmitter.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at EventEmitter.exports.setLhs (/home/ose/ose-example-rpi/node_modules/ose/lib/subject.js:94:8)
========================================================
</code></pre>

**Comment by FredRooks** [comment]
The problem is permissions-related and goes away after adding the present user to the `gpio` group. The example should handle this situation gracefully.
